# Generated by Django 4.2.16 on 2024-10-28 09:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("flex_page", "0004_alter_flexpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section Title",
                                        max_length=100,
                                        verbose_name="Section Title",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "underline",
                                            "strikethrough",
                                            "superscript",
                                            "subscript",
                                            "h1",
                                            "h2",
                                            "h3",
                                            "h4",
                                            "h5",
                                            "h6",
                                            "blockquote",
                                            "code",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                            "image",
                                            "embed",
                                            "hr",
                                            "anchor",
                                            "table",
                                            "justifyLeft",
                                            "justifyCenter",
                                            "justifyRight",
                                            "justifyFull",
                                            "indent",
                                            "outdent",
                                            "html",
                                        ],
                                        help_text="Section description",
                                        verbose_name="Section Text",
                                    ),
                                ),
                                (
                                    "action_link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=15, required=False
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("center", "Center")]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "title_text_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section Title",
                                        max_length=100,
                                        verbose_name="Section Title",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "ul",
                                            "ol",
                                            "link",
                                            "superscript",
                                            "subscript",
                                            "h2",
                                            "h3",
                                            "h4",
                                        ],
                                        help_text="Section description",
                                        verbose_name="Section Text",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "action_link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=15, required=False
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                                (
                                    "img_postn",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Image before Text",
                                        required=True,
                                        verbose_name="Image Before Text",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "collapsibles",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "collapsibles",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "ul",
                                                                    "ol",
                                                                    "link",
                                                                    "superscript",
                                                                    "subscript",
                                                                    "h2",
                                                                    "h3",
                                                                    "h4",
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "feature_item",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "features",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "features",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "ul",
                                                                    "ol",
                                                                    "link",
                                                                    "superscript",
                                                                    "subscript",
                                                                    "h2",
                                                                    "h3",
                                                                    "h4",
                                                                ],
                                                                label="Description",
                                                            ),
                                                        ),
                                                        (
                                                            "action_link_text",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=15,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "action_link",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Action Link Internal",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "action_link_external",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                                                max_length=400,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "dark_mode",
                                                            wagtail.blocks.BooleanBlock(
                                                                bool=False,
                                                                help_text="Switch Section to dark mode",
                                                                required=True,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "ul",
                                            "ol",
                                            "link",
                                            "superscript",
                                            "subscript",
                                            "h2",
                                            "h3",
                                            "h4",
                                        ],
                                        label="Description",
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Quote Text",
                                        max_length=100,
                                        verbose_name="Quote Text",
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "title_text_icons",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "display",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("list", "List"), ("grid", "Grid")]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "ul",
                                                                    "ol",
                                                                    "link",
                                                                    "superscript",
                                                                    "subscript",
                                                                    "h2",
                                                                    "h3",
                                                                    "h4",
                                                                ],
                                                                label="Description",
                                                            ),
                                                        ),
                                                        (
                                                            "action_link",
                                                            wagtail.blocks.PageChooserBlock(
                                                                label="Action Link Internal",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "action_link_external",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                                                max_length=400,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
