# Generated by Django 4.2.16 on 2024-10-28 08:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Flexible Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="align",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")],
                default="left",
                max_length=50,
                verbose_name="Align Content",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                help_text="A high quality banner image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Banner Subtitle"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Introduction Text"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Banner Title"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="call_to_action_button_text",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Call to action button text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="call_to_action_related_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Call to action related page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section Title",
                                        max_length=100,
                                        verbose_name="Section Title",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "underline",
                                            "strikethrough",
                                            "superscript",
                                            "subscript",
                                            "h1",
                                            "h2",
                                            "h3",
                                            "h4",
                                            "h5",
                                            "h6",
                                            "blockquote",
                                            "code",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                            "image",
                                            "embed",
                                            "hr",
                                            "anchor",
                                            "table",
                                            "justifyLeft",
                                            "justifyCenter",
                                            "justifyRight",
                                            "justifyFull",
                                            "indent",
                                            "outdent",
                                            "html",
                                        ],
                                        help_text="Section description",
                                        verbose_name="Section Text",
                                    ),
                                ),
                                (
                                    "action_link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=15, required=False
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                                (
                                    "align",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("center", "Center")]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "title_text_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section Title",
                                        max_length=100,
                                        verbose_name="Section Title",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "ul",
                                            "ol",
                                            "link",
                                            "superscript",
                                            "subscript",
                                            "h2",
                                            "h3",
                                            "h4",
                                        ],
                                        help_text="Section description",
                                        verbose_name="Section Text",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "action_link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=15, required=False
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                                (
                                    "img_postn",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Image before Text",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "collapsibles",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "collapsibles",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "ul",
                                                                    "ol",
                                                                    "link",
                                                                    "superscript",
                                                                    "subscript",
                                                                    "h2",
                                                                    "h3",
                                                                    "h4",
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "feature_item",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "ul",
                                            "ol",
                                            "link",
                                            "superscript",
                                            "subscript",
                                            "h2",
                                            "h3",
                                            "h4",
                                        ],
                                        label="Description",
                                    ),
                                ),
                                (
                                    "action_link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=15, required=False
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "ul",
                                            "ol",
                                            "link",
                                            "superscript",
                                            "subscript",
                                            "h2",
                                            "h3",
                                            "h4",
                                        ],
                                        label="Description",
                                    ),
                                ),
                                (
                                    "action_link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Action Link Internal", required=False
                                    ),
                                ),
                                (
                                    "action_link_external",
                                    wagtail.blocks.URLBlock(
                                        help_text="An external link to a detailed resource on the internet.If provided, the internal link will be ignored",
                                        max_length=400,
                                        required=False,
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Quote Text",
                                        max_length=100,
                                        verbose_name="Quote Text",
                                    ),
                                ),
                                (
                                    "dark_mode",
                                    wagtail.blocks.BooleanBlock(
                                        bool=False,
                                        help_text="Switch Section to dark mode",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
    ]
