# Generated by Django 4.2.16 on 2024-10-28 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
    ]
